"""Add report cache table

Revision ID: 371e5742e34b
Revises: f6004ed9ec4b
Create Date: 2025-07-12 18:14:11.685144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371e5742e34b'
down_revision = 'f6004ed9ec4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('report_data', sa.Text(), nullable=True),
    sa.Column('category_totals', sa.Text(), nullable=True),
    sa.Column('grand_totals', sa.Text(), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_report_cache_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_cache'))
    )
    with op.batch_alter_table('report_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_cache_expires_at'), ['expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_cache_expires_at'))

    op.drop_table('report_cache')
    # ### end Alembic commands ###
