"""Change unit_price to Numeric for precision

Revision ID: 75071e9fb567
Revises: 371e5742e34b
Create Date: 2025-07-17 00:24:39.226154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75071e9fb567'
down_revision = '371e5742e34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.alter_column('unit_price',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.alter_column('unit_price',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.alter_column('unit_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.alter_column('unit_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
