"""Add ondelete cascade to foreign keys for inventory ids 

Revision ID: b483f4261e9a
Revises: 722ad6550f37
Create Date: 2025-06-25 19:50:05.166141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b483f4261e9a'
down_revision = '722ad6550f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inventory_transactions_inventory_id_inventories', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_inventory_transactions_inventory_id_inventories'), 'inventories', ['inventory_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inventory_transactions_inventory_id_inventories'), type_='foreignkey')
        batch_op.create_foreign_key('fk_inventory_transactions_inventory_id_inventories', 'inventories', ['inventory_id'], ['id'])

    # ### end Alembic commands ###
