"""Added local authentication fields for testing only

Revision ID: f6004ed9ec4b
Revises: 48ae8da88d6a
Create Date: 2025-07-05 19:11:55.148597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6004ed9ec4b'
down_revision = '48ae8da88d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('auth_method', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('auth_method')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
